# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: AzurePowerShell@5
  inputs:
    azureSubscription: 'Azure Pass - Sponsorship (3a82d220-6df1-4044-9abf-6f33a3ae371f)'
    ScriptType: 'FilePath'
    ScriptPath: 'azure.ps1'
    ScriptArguments: '-path "./" -OutputFile "TEST-Pester.xml" -OutputFormat NUnitXml'
    azurePowerShellVersion: 'LatestVersion'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'NUnit'
    testResultsFiles: 'TEST-Pester.xml'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'NUnit'
    testResultsFiles: 'TEST-Pester.xml'
    searchFolder: './'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'NUnit'
    testResultsFiles: 'TEST-Pester.xml'
    searchFolder: './$(System.DefaultWorkingDirectory)'



